"""ExtendScript (ES3) emitter: JS literals, the runtime prelude (keyframes with Rive eases, layers, text, mattes)."""
import math


def js(v):
    """Python -> JS literal, ASCII only (ExtendScript mangles UTF-8)."""
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        if isinstance(v, float) and (math.isnan(v) or math.isinf(v)):
            v = 0.0
        s = f"{v:.6f}".rstrip("0").rstrip(".") if isinstance(v, float) else str(v)
        return s if s not in ("", "-0") else "0"
    if isinstance(v, str):
        out = []
        for ch in v:
            o = ord(ch)
            if ch == '"':
                out.append('\\"')
            elif ch == "\\":
                out.append("\\\\")
            elif ch == "\n":
                out.append("\\n")
            elif ch == "\r":
                out.append("\\r")
            elif 32 <= o < 127:
                out.append(ch)
            else:
                out.append(f"\\u{o:04x}")
        return '"' + "".join(out) + '"'
    if isinstance(v, (list, tuple)):
        return "[" + ",".join(js(x) for x in v) + "]"
    if isinstance(v, dict):
        return "{" + ",".join(f"{js(str(k))}: {js(x)}" for k, x in v.items()) + "}"
    if v is None:
        return "null"
    raise TypeError(type(v))


class Writer:
    def __init__(self):
        self.lines = []
        self.n = 0

    def var(self, prefix="v"):
        self.n += 1
        return f"{prefix}{self.n}"

    def __call__(self, line):
        self.lines.append(line)

    def text(self):
        return "\n".join(self.lines)


# Every rule below was measured in AE 2026 (see RIVE_FILM_GUIDELINES.md §5): keyframe times are comp times,
# interpolation types BEZIER first then eases then HOLD last, `parent` keeps the child's world transform, nulls are
# solids at opacity 0, temporal eases of Scale on a 2D layer are 3-dimensional.
PRELUDE = r"""
// ---- generated by rml2ae — regenerate, do not edit ----
var FPS = __FPS__;
var LOGF = new File(__LOG__);
LOGF.open("w"); LOGF.close();
function log(s) { LOGF.open("a"); LOGF.write(s + "\n"); LOGF.close(); }
function T(f) { return f / FPS; }
function clamp(v, a, b) { return v < a ? a : (v > b ? b : v); }
function tr(layer, name) { return layer.property("ADBE Transform Group").property(name); }
// a child inherits its parent's opacity (Rive semantics); a data-binding expression already on the child is kept and multiplied
function propagateOpacity(layer) {
  var op = tr(layer, "ADBE Opacity"); var e = op.expression;
  if (e && e.indexOf("thisLayer.parent.transform.opacity") >= 0) return;
  op.expression = e ? "(" + e + ") * thisLayer.parent.transform.opacity / 100" : "value * thisLayer.parent.transform.opacity / 100";
}
// ---- element tags (incremental rebuilds): every layer of an element carries its Rive id in `comment`
// (main layer: "rive:<id>", helpers: "rive:<id>+…"); the comp background carries "head+"
function layerTag(comp, tag) { if (!comp) return null; for (var i = 1; i <= comp.numLayers; i++) if (comp.layer(i).comment == tag) return comp.layer(i); return null; }
function hasTag(L, tags) { var c = L.comment || ""; if (!c) return false; for (var k = 0; k < tags.length; k++) if (c == tags[k] || c.indexOf(tags[k] + "+") == 0) return true; return false; }
function layerIds(comp) { var m = {}; if (!comp) return m; for (var i = 1; i <= comp.numLayers; i++) m[comp.layer(i).id] = true; return m; }
function newLayers(comp, ids) {               // the layers added since the `ids` snapshot, top to bottom (wherever they are)
  var out = []; if (!comp) return out;
  for (var i = 1; i <= comp.numLayers; i++) { var L = comp.layer(i); if (!ids[L.id]) out.push(L); }
  return out;
}
function tagNew(comp, ids, tag, main) {          // the layers added since `ids` belong to `tag`
  var Ls = newLayers(comp, ids);
  for (var i = 0; i < Ls.length; i++) { var L = Ls[i]; if (main && L === main) L.comment = tag; else if (!L.comment) L.comment = tag + "+"; else if (L.comment == tag) L.comment = tag + "+dup"; roleLabel(L); }
}
// one label per role, the same in every project (audit F27: only nulls had one, the rest took this machine's defaults):
// shape 8 blue, text 2 yellow, footage 13 fuchsia, precomp 15 sandstone, colour solid 7 sea foam, baked (replay /
// skinned) 12 brown; technical helpers (mattes, clip duplicates, feather solids) 0 none + shy — hidden in one click
// with the comp's shy switch; nulls keep their role label (controller 3, bone 10, placeholder 4, ViewModel 9)
function roleLabel(L) {
  try {
    var c = L.comment || "", n = L.name || "";
    if (c.indexOf("+matte") >= 0 || c.indexOf("+dup") >= 0 || c.indexOf("+feather") >= 0 || n.indexOf("(matte)") >= 0) { L.label = 0; L.shy = true; return; }
    if (n.indexOf("[replay]") == 0 || n.indexOf("[skinned]") >= 0) { L.label = 12; return; }
    if (L.nullLayer) return;
    if (L instanceof ShapeLayer) { L.label = 8; return; }
    if (L instanceof TextLayer) { L.label = 2; return; }
    if (L.source instanceof CompItem) { L.label = 15; return; }
    if (L.source && L.source.mainSource instanceof SolidSource) { L.label = 7; return; }
    L.label = 13;
  } catch (e) {}
}
function removeTagged(comp, tags) { var n = 0; if (!comp) return 0; for (var i = comp.numLayers; i >= 1; i--) if (hasTag(comp.layer(i), tags)) { comp.layer(i).remove(); n++; } return n; }
function topOf(comp, tags) { if (!comp) return null; for (var i = 1; i <= comp.numLayers; i++) if (hasTag(comp.layer(i), tags)) return comp.layer(i); return null; }
function belowOf(comp, tags) {                   // {below: layer under the lowest tagged one (null = bottom)} or null if none
  var low = 0; if (!comp) return null; for (var i = 1; i <= comp.numLayers; i++) if (hasTag(comp.layer(i), tags)) low = i;
  if (!low) return null; return { below: low < comp.numLayers ? comp.layer(low + 1) : null };
}
// where a rebuilt element goes in the stack: where its old layers were, else above the previous sibling, else at the
// bottom of its parent's subtree, else above the comp background (null = bottom of the comp)
function anchor(comp, own, prev, par) {
  var r = belowOf(comp, own); if (r) return r.below;
  if (prev.length) { var t = topOf(comp, prev); if (t) return t; }
  if (par.length) { r = belowOf(comp, par); if (r) return r.below; }
  return topOf(comp, ["head"]);
}
function placeNew(comp, ids, below) {           // the layers added since `ids` move as a block to sit right above `below`
  var Ls = newLayers(comp, ids); var k = Ls.length; if (k <= 0) return;
  for (var i = 0; i < k; i++) if (Ls[i] === below) { below = (i + 1 < k) ? null : below; if (below === null) { log("placeNew: anchor is a new layer, block left in place"); return; } }
  if (below) Ls[k - 1].moveBefore(below); else Ls[k - 1].moveToEnd();
  for (var j = k - 2; j >= 0; j--) Ls[j].moveBefore(Ls[j + 1]);
}
function propUnder(comp, ids, par) {            // new layers parented to `par` read its opacity (Rive multiplies it down)
  if (!par) return; var Ls = newLayers(comp, ids);
  for (var i = 0; i < Ls.length; i++) if (Ls[i].parent && Ls[i].parent.index == par.index) propagateOpacity(Ls[i]);
}
// an AE effect declared in the RML (<!-- ae: … -->, rml2ae/effects.py): matchName + parameter slots
function addFx(L, match, params) {
  var fx = L.property("ADBE Effect Parade").addProperty(match);
  for (var k in params) { try { fx.property(k).setValue(params[k]); } catch (e) { log("effect " + match + " param " + k + ": " + e.toString()); } }
  return fx;
}
// a layer only exists while its element can be seen (its opacity and its ancestors' are not 0): the cut is in its in/out
// points, as an editor would make it (the opacity keys stay: they also draw any gap inside the window)
function trimTo(L, a, b) {
  if (!L || L.inPoint === undefined) return;
  var i = Math.max(L.inPoint, a), o = Math.min(L.outPoint, b);
  if (o - i > 1e-6) { if (i > L.inPoint) L.inPoint = i; if (o < L.outPoint) L.outPoint = o; }
}
function resetProp(p, v) { while (p.numKeys > 0) p.removeKey(1); p.expression = ""; p.setValue(v); }
// a clip source copy turned into the stencil of its clipped precomp: geometry only (Rive clips by the path, not by its
// paint): fills opaque and unkeyed, strokes removed, layer opacity 100, Stencil Alpha, on top of the precomp's stack
function stencilize(L) {
  function walk(g) {
    for (var i = g.numProperties; i >= 1; i--) {
      var q = g.property(i), mn = q.matchName;
      if (mn == "ADBE Vector Graphic - Stroke") { q.remove(); continue; }
      if (mn == "ADBE Vector Graphic - Fill") { resetProp(q.property("ADBE Vector Fill Opacity"), 100); continue; }
      if (mn == "ADBE Vector Group") walk(q.property("ADBE Vectors Group"));
    }
  }
  try { walk(L.property("ADBE Root Vectors Group")); } catch (e) {}
  resetProp(tr(L, "ADBE Opacity"), 100);
  L.blendingMode = BlendingMode.STENCIL_ALPHA;
  L.moveToBeginning();
}
function sep(layer) { tr(layer, "ADBE Position").dimensionsSeparated = true; }
// after `layer.parent = X` AE rewrites the child's transform to keep its world transform: reset it explicitly
function resetTf(layer, ax, ay, x, y) {
  tr(layer, "ADBE Anchor Point").setValue([ax, ay]); tr(layer, "ADBE Position").setValue([x, y]);
  tr(layer, "ADBE Rotate Z").setValue(0); tr(layer, "ADBE Scale").setValue([100, 100]);
}
// the Rive Shader plugin (rml2ae/plugin) runs .wgsl post-process shaders as is when it is installed
var RIVE_SHADER = (function () { try { for (var i = 0; i < app.effects.length; i++) { if (app.effects[i].matchName == "RIVE RiveShader") return true; } } catch (e) {} return false; })();
// ---- passes for the Rive Shader plugin: clone a comp tree bound to a ViewModel copy with overridden values
// expression sources keep the \uXXXX escapes rml2ae wrote: match both the escaped and the raw spelling of a name
function jsEsc(s) { var o = ""; for (var i = 0; i < s.length; i++) { var c = s.charCodeAt(i); o += c > 127 ? "\\u" + ("0000" + c.toString(16)).slice(-4) : s.charAt(i); } return o; }
function compByName(n) { for (var i = 1; i <= app.project.numItems; i++) { var it = app.project.item(i); if (it instanceof CompItem && it.name == n) return it; } return null; }
function cloneVm(vmComp, newName, overrides) {
  var d = vmComp.duplicate(); d.name = newName;
  var L = d.layer("ViewModel"); if (!L) return d;
  for (var k in overrides) {
    var fx = L.property("ADBE Effect Parade").property(k); if (!fx) { log("cloneVm: no VM property " + k); continue; }
    var v = overrides[k];
    if (fx.matchName == "ADBE Checkbox Control") fx.property(1).setValue(v ? 1 : 0);
    else if (fx.matchName == "ADBE Slider Control") fx.property(1).setValue(Number(v));
    else if (fx.matchName == "ADBE Color Control") fx.property(1).setValue(v);
  }
  return d;
}
function rewriteExpr(prop, pairs) {
  for (var i = 1; i <= prop.numProperties; i++) {
    var q = prop.property(i);
    if (q.propertyType == PropertyType.PROPERTY) {
      try { if (q.canSetExpression && q.expression) { var e = q.expression, e0 = e; for (var j = 0; j < pairs.length; j++) e = e.split(pairs[j][0]).join(pairs[j][1]); if (e != e0) q.expression = e; } } catch (er) {}
    } else rewriteExpr(q, pairs);
  }
}
function setVm(vmComp, overrides) {
  var L = vmComp.layer("ViewModel"); if (!L) return;
  for (var k in overrides) {
    var fx = L.property("ADBE Effect Parade").property(k); if (!fx) { log("setVm: no VM property " + k); continue; }
    var v = overrides[k];
    if (fx.matchName == "ADBE Checkbox Control") fx.property(1).setValue(v ? 1 : 0);
    else if (fx.matchName == "ADBE Slider Control") fx.property(1).setValue(Number(v));
    else if (fx.matchName == "ADBE Color Control") fx.property(1).setValue(v);
  }
}
function exprMentions(prop, pairs) {
  for (var i = 1; i <= prop.numProperties; i++) {
    var q = prop.property(i);
    if (q.propertyType == PropertyType.PROPERTY) {
      try { if (q.canSetExpression && q.expression) { for (var j = 0; j < pairs.length; j++) if (q.expression.indexOf(pairs[j][0]) >= 0) return true; } } catch (er) {}
    } else if (exprMentions(q, pairs)) return true;
  }
  return false;
}
// does `comp` (or a comp below it) read one of the VM comps of `pairs` through an expression? (memo by comp id)
function dependsOnVm(comp, pairs, memo) {
  if (memo[comp.id] !== undefined) return memo[comp.id];
  memo[comp.id] = false;
  var r = false;
  for (var i = 1; i <= comp.numLayers && !r; i++) {
    var L = comp.layer(i);
    if (L.source instanceof CompItem && dependsOnVm(L.source, pairs, memo)) r = true;
    else if (exprMentions(L, pairs)) r = true;
  }
  memo[comp.id] = r;
  return r;
}
// duplicate `comp` and every comp reachable through its layers that reads the ViewModel (not the VM comps, reached by
// expressions only; comps that never read it stay shared, audit F1), then point every expression at the VM copy
// (pairs = [[from, to], ...]); memo keeps shared precomps shared
function cloneTree(comp, suffix, pairs, memo, dep) {
  if (memo[comp.id]) return memo[comp.id];
  if (!dep) dep = {};
  if (!dependsOnVm(comp, pairs, dep)) return comp;
  var d = comp.duplicate(); d.name = comp.name + " [" + suffix + "]"; d.parentFolder = comp.parentFolder; memo[comp.id] = d;
  for (var i = 1; i <= d.numLayers; i++) {
    var L = d.layer(i);
    if (L.source instanceof CompItem) { var c2 = cloneTree(L.source, suffix, pairs, memo, dep); if (c2.id != L.source.id) L.replaceSource(c2, false); }
  }
  for (var i = 1; i <= d.numLayers; i++) rewriteExpr(d.layer(i), pairs);
  return d;
}
function slider(layer, name, value) {
  var fx = layer.property("ADBE Effect Parade").addProperty("ADBE Slider Control");
  fx.name = name; fx.property("ADBE Slider Control-0001").setValue(value); return fx.property("ADBE Slider Control-0001");
}
// footage is reused when the same file is already in the project (incremental rebuilds never duplicate imports)
function importFile(path) {
  var f = new File(path);
  if (!f.exists) throw new Error("missing file " + path);
  for (var i = 1; i <= app.project.numItems; i++) {
    var it = app.project.item(i);
    try { if (it instanceof FootageItem && it.file && it.file.fsName == f.fsName) return it; } catch (e) {}
  }
  return app.project.importFile(new ImportOptions(f));
}
function folder(parent, name) {
  for (var i = 1; i <= app.project.numItems; i++) {
    var it = app.project.item(i);
    if (it instanceof FolderItem && it.name == name && ((parent && it.parentFolder.id == parent.id) || (!parent && it.parentFolder == app.project.rootFolder))) return it;
  }
  var f = app.project.items.addFolder(name); if (parent) f.parentFolder = parent; return f;
}
// comps we made, by their "rive:…" / "vm:…" comment tag
function compTags() {
  var m = {};
  for (var i = 1; i <= app.project.numItems; i++) {
    var it = app.project.item(i);
    if (it instanceof CompItem && it.comment && (it.comment.indexOf("rive:") == 0 || it.comment.indexOf("vm:") == 0)) m[it.comment] = it;
  }
  return m;
}
// helper comps (no rive tag) in a folder that nothing uses any more
function cleanupUnused(folderItem) {
  var n = 0;
  for (var i = app.project.numItems; i >= 1; i--) {
    var it = app.project.item(i);
    if (it instanceof CompItem && it.parentFolder && it.parentFolder.id == folderItem.id && !(it.comment && it.comment.length) && it.usedIn.length == 0) { it.remove(); n++; }
  }
  if (n) log("removed " + n + " unused helper comp(s)");
}
// every layer that uses oldComp as its source now uses newComp (its transform, effects and keys are untouched)
function relinkComp(oldComp, newComp) {
  var n = 0;
  for (var i = 1; i <= app.project.numItems; i++) {
    var it = app.project.item(i);
    if (!(it instanceof CompItem) || it === oldComp) continue;
    for (var j = 1; j <= it.numLayers; j++) {
      var L = it.layer(j);
      try { if (L.source && L.source === oldComp) { L.replaceSource(newComp, false); n++; } } catch (e) {}
    }
  }
  log("relinked " + n + " layer(s) of " + newComp.name);
}
function shapeFrom(verts, ins, outs, closed) {
  var s = new Shape(); s.vertices = verts; s.inTangents = ins; s.outTangents = outs; s.closed = closed; return s;
}
var BLEND = { srcOver: BlendingMode.NORMAL, screen: BlendingMode.SCREEN, overlay: BlendingMode.OVERLAY, darken: BlendingMode.DARKEN,
  lighten: BlendingMode.LIGHTEN, colorDodge: BlendingMode.COLOR_DODGE, colorBurn: BlendingMode.COLOR_BURN, hardLight: BlendingMode.HARD_LIGHT,
  softLight: BlendingMode.SOFT_LIGHT, difference: BlendingMode.DIFFERENCE, exclusion: BlendingMode.EXCLUSION, multiply: BlendingMode.MULTIPLY,
  hue: BlendingMode.HUE, saturation: BlendingMode.SATURATION, color: BlendingMode.COLOR, luminosity: BlendingMode.LUMINOSITY };
// keyframes. ks = [[frame, value, kind, x1, y1, x2, y2], ...]; kind "h" hold / "l" linear / "c" CSS cubic-bezier of the
// segment that STARTS at this key (Rive semantics). Values: number, [x,y], [r,g,b,a] or a Shape.
// time remap: enabling it makes two default keys (0 and the source end) that stay mixed with ours and shift keys()'
// interpolation-by-index (measured: a nested shot starting before its own duration froze on its first frame).
// Set ours first, THEN drop every other key (dropping all keys first would disable the remap).
function dropOtherKeys(p, times) {
  for (var k = p.numKeys; k >= 1; k--) {
    var t = p.keyTime(k), keep = false;
    for (var i = 0; i < times.length; i++) if (Math.abs(times[i] - t) < 1e-4) { keep = true; break; }
    if (!keep) p.removeKey(k);
  }
}
function remapKeys(p, ks) {
  var times = [];
  for (var i = 0; i < ks.length; i++) { p.setValueAtTime(T(ks[i][0]), ks[i][1]); times.push(T(ks[i][0])); }
  dropOtherKeys(p, times);
  keys(p, ks);
}
function remapSet(p, pairs) {
  var times = [];
  for (var i = 0; i < pairs.length; i++) { p.setValueAtTime(pairs[i][0], pairs[i][1]); times.push(pairs[i][0]); }
  dropOtherKeys(p, times);
}
function keys(p, ks) {
  if (ks.length == 0) return;
  if (ks.length == 1) { p.setValue(ks[0][1]); return; }
  var n = ks.length, i;
  for (i = 0; i < n; i++) p.setValueAtTime(T(ks[i][0]), ks[i][1]);
  var B = KeyframeInterpolationType.BEZIER, HLD = KeyframeInterpolationType.HOLD;
  var isShape = (ks[0][1] instanceof Shape);
  if (isShape) { for (i = 0; i < n - 1; i++) if (ks[i][2] == "h") p.setInterpolationTypeAtKey(i + 1, p.keyInInterpolationType(i + 1), HLD); return; }
  var dims = (ks[0][1] instanceof Array) ? ks[0][1].length : 1;
  var spatial = false;
  try { spatial = p.isSpatial; } catch (e) {}
  for (i = 0; i < n; i++) p.setInterpolationTypeAtKey(i + 1, B, B);
  var nEase = p.keyInTemporalEase(1).length;
  var eases = [];
  for (i = 0; i < n; i++) eases.push([p.keyInTemporalEase(i + 1), p.keyOutTemporalEase(i + 1)]);
  for (i = 0; i < n - 1; i++) {
    var kind = ks[i][2];
    if (kind == "h") continue;
    var lin = (kind == "l");
    var x1 = lin ? 0.3333 : ks[i][3], y1 = lin ? 0.3333 : ks[i][4], x2 = lin ? 0.6667 : ks[i][5], y2 = lin ? 0.6667 : ks[i][6];
    var dt = T(ks[i + 1][0]) - T(ks[i][0]);
    var outE = [], inE = [];
    for (var d = 0; d < nEase; d++) {
      var dd = Math.min(d, dims - 1);
      var v0 = dims > 1 ? ks[i][1][dd] : ks[i][1], v1 = dims > 1 ? ks[i + 1][1][dd] : ks[i + 1][1];
      var dv = v1 - v0;
      if (spatial && dims > 1) { dv = 0; for (var q = 0; q < dims; q++) dv += Math.pow(ks[i + 1][1][q] - ks[i][1][q], 2); dv = Math.sqrt(dv); }
      // speed at the influence actually written (0.1 % minimum): a vertical handle (x1 = 0 or x2 = 1) is a very fast
      // start / end, not a zero speed (walk-test: 'Ecran fond' exit was 272 px off with so = 0)
      var ix = Math.max(x1, 0.001), ox = Math.max(1 - x2, 0.001);
      var so = (y1 * dv) / (ix * dt);
      var si = ((1 - y2) * dv) / (ox * dt);
      if (isNaN(so) || !isFinite(so)) so = 0;
      if (isNaN(si) || !isFinite(si)) si = 0;
      outE.push(new KeyframeEase(so, clamp(x1 * 100, 0.1, 100)));
      inE.push(new KeyframeEase(si, clamp((1 - x2) * 100, 0.1, 100)));
    }
    eases[i][1] = outE; eases[i + 1][0] = inE;
  }
  for (i = 0; i < n; i++) { try { p.setTemporalEaseAtKey(i + 1, eases[i][0], eases[i][1]); } catch (e3) {} }
  // a Rive linear segment is LINEAR on both of its sides (the Graph Editor shows a straight line and a retime keeps it);
  // the order BEZIER, eases, then LINEAR / HOLD is the measured one
  var LIN = KeyframeInterpolationType.LINEAR;
  for (i = 0; i < n - 1; i++) if (ks[i][2] == "l") {
    p.setInterpolationTypeAtKey(i + 1, p.keyInInterpolationType(i + 1), LIN);
    p.setInterpolationTypeAtKey(i + 2, LIN, p.keyOutInterpolationType(i + 2));
  }
  // nothing follows the last key: its out side follows its in side instead of a HOLD that bites when extending
  for (i = 0; i < n - 1; i++) if (ks[i][2] == "h") p.setInterpolationTypeAtKey(i + 1, p.keyInInterpolationType(i + 1), HLD);
  if (n > 1) { try { p.setInterpolationTypeAtKey(n, p.keyInInterpolationType(n), p.keyInInterpolationType(n)); } catch (e4) {} }
  if (spatial) { for (i = 1; i <= n; i++) { try { p.setSpatialTangentsAtKey(i, [0, 0], [0, 0]); } catch (e2) {} } }
}
var BOXPOS_LOGGED = false;
function textLayer(comp, txt, font, size, rgb, justify, tracking, leading, boxW, boxH) {
  var L = (boxW > 0) ? comp.layers.addBoxText([boxW, boxH > 0 ? boxH : 4000], txt) : comp.layers.addText(txt);
  var d = L.property("ADBE Text Properties").property("ADBE Text Document");
  var td = d.value;
  td.font = font; td.fontSize = size; td.fillColor = rgb; td.applyFill = true; td.applyStroke = false;
  td.justification = justify; td.tracking = tracking || 0;
  if (leading > 0) { td.autoLeading = false; td.leading = leading; }
  d.setValue(td);
  if (boxW > 0 && !BOXPOS_LOGGED) { BOXPOS_LOGGED = true; try { log("boxTextPos of the first box text: " + d.value.boxTextPos + " size " + d.value.boxTextSize); } catch (eb) { log("boxTextPos unreadable"); } }
  return L;
}
function textStroke(L, rgb, width) {
  var d = L.property("ADBE Text Properties").property("ADBE Text Document"); var td = d.value;
  td.applyStroke = true; td.strokeColor = rgb; td.strokeWidth = width; td.strokeOverFill = false; d.setValue(td);
}
// text animator: props = {pos:[x,y], rot:deg, opacity:0..100, scale:[x,y]} ; sel = {units:"words"|"lines"|"characters", start, end, index:true}
function animator(L, name, props, sel) {
  var an = L.property("ADBE Text Properties").property("ADBE Text Animators").addProperty("ADBE Text Animator");
  an.name = name;
  var ap = an.property("ADBE Text Animator Properties");
  var out = { anim: an };
  if (props.pos !== undefined) out.pos = ap.addProperty("ADBE Text Position 3D");
  if (props.rot !== undefined) out.rot = ap.addProperty("ADBE Text Rotation");
  if (props.opacity !== undefined) out.opacity = ap.addProperty("ADBE Text Opacity");
  if (props.scale !== undefined) out.scale = ap.addProperty("ADBE Text Scale 3D");
  if (out.pos) out.pos.setValue([props.pos[0], props.pos[1], 0]);
  if (out.rot) out.rot.setValue(props.rot);
  if (out.opacity) out.opacity.setValue(props.opacity);
  if (out.scale) out.scale.setValue([props.scale[0], props.scale[1], 100]);
  var s = an.property("ADBE Text Selectors").addProperty("ADBE Text Selector");
  var adv = s.property("ADBE Text Range Advanced");
  var based = { characters: 1, charactersNoSpaces: 2, words: 3, lines: 4 }[sel.units || "characters"];
  adv.property("ADBE Text Range Type2").setValue(based);
  if (sel.index) {
    adv.property("ADBE Text Range Units").setValue(2);
    out.start = s.property("ADBE Text Index Start"); out.end = s.property("ADBE Text Index End");
  } else {
    adv.property("ADBE Text Range Units").setValue(1);
    out.start = s.property("ADBE Text Percent Start"); out.end = s.property("ADBE Text Percent End");
  }
  out.start.setValue(sel.start); out.end.setValue(sel.end);
  out.amount = adv.property("ADBE Text Selector Max Amount");
  return out;
}
// source text keyframes (always hold): rows = [[frame, "text"], ...] — keeps the layer's text style
function textKeys(L, rows) {
  var d = L.property("ADBE Text Properties").property("ADBE Text Document");
  for (var i = 0; i < rows.length; i++) { var td = d.value; td.text = rows[i][1]; d.setValueAtTime(T(rows[i][0]), td); }
}
// per-run style (AE 2024+ characterRange); silently skipped on older versions
function runStyle(L, start, len, font, size, rgb) {
  try {
    var d = L.property("ADBE Text Properties").property("ADBE Text Document"); var td = d.value;
    var cr = td.characterRange(start, start + len);
    if (font) cr.font = font; if (size > 0) cr.fontSize = size; if (rgb) cr.fillColor = rgb;
    d.setValue(td);
  } catch (e) { log("runStyle unsupported on this AE: " + e.toString()); }
}
function selfTest(comp) {
  var n = comp.layers.addNull(); n.name = "__selftest";
  var p = slider(n, "t", 0);
  keys(p, [[0, 0, "c", 0.5, 0, 0.05, 1], [20, 100, "h"], [30, 0, "l"], [40, 50, "h"]]);
  var s = "selftest (expect 19.63 83.07 97.08 100 25):";
  var pr = [5, 10, 15, 25, 35];
  for (var i = 0; i < pr.length; i++) s += " " + p.valueAtTime(T(pr[i]), false).toFixed(2);
  s += " linear=" + (p.keyOutInterpolationType(3) == KeyframeInterpolationType.LINEAR && p.keyInInterpolationType(4) == KeyframeInterpolationType.LINEAR);
  log(s);
  // vertical handles (CSS 0,0.58,0.36,1 and 0.65,0,1,0.4): Rive progress at 0.1 / 0.5 / 0.9
  var q = slider(n, "v", 0);
  keys(q, [[0, 0, "c", 0.001, 0.58, 0.36, 1], [10, 100, "c", 0.65, 0, 0.999, 0.4], [20, 0, "h"]]);
  var s2 = "selftest vertical handles (Rive: 48.25 89.28 99.65 | 99.67 89.87 49.56):";
  var pr2 = [1, 5, 9, 11, 15, 19];
  for (var j = 0; j < pr2.length; j++) s2 += " " + q.valueAtTime(T(pr2[j]), false).toFixed(2);
  log(s2);
  n.remove();
}
"""

# ---- tidy: nulls that do nothing are dissolved once the build is done (measured on a 72 s film: 1 456 nulls for
# 1 443 shape layers, 275 of them with no child). A null goes when it is static (no keys, no expression but the
# opacity propagation, opacity 100 %, no effect, 2D) and its children can take its transform: AE re-expresses each
# child in the grandparent's space when its parent changes, keys included (measured 2026-10-07: identical world
# positions at 5 times). What a dissolved null was is kept in the comment of a folder item ("rml2ae tidy"), keyed by
# comp id + child layer id, so that `ae pull` puts the null back for the time it reads the child (rml2ae/pull.py).
TIDY_JSX = r"""
var PROPAGATE = "value * thisLayer.parent.transform.opacity / 100";
function tidyR(v) { return Math.round(v * 1e6) / 1e6; }
function tidyTf(L) {
  var t = L.property("ADBE Transform Group"), p = t.property("ADBE Position"), a = t.property("ADBE Anchor Point").value, s = t.property("ADBE Scale").value;
  var pv = p.dimensionsSeparated ? [t.property("ADBE Position_0").value, t.property("ADBE Position_1").value] : p.value;
  return [tidyR(a[0]), tidyR(a[1]), tidyR(pv[0]), tidyR(pv[1]), tidyR(t.property("ADBE Rotate Z").value), tidyR(s[0]), tidyR(s[1])];
}
function tidySer(o) {
  var out = [];
  function v(x) { return typeof x == "string" ? '"' + x.replace(/\\/g, "\\\\").replace(/"/g, '\\"') + '"' : String(x); }
  for (var k in o) { var ch = o[k], parts = []; for (var i = 0; i < ch.length; i++) { var row = []; for (var j = 0; j < ch[i].length; j++) row.push(v(ch[i][j])); parts.push("[" + row.join(",") + "]"); } out.push('"' + k + '":[' + parts.join(",") + "]"); }
  return "{" + out.join(",") + "}";
}
// the store: a folder "rml2ae tidy" whose sub-folders "1", "2"… carry the text in their comments (AE caps an item
// comment at 15 999 bytes)
function tidyStore(root) {
  for (var i = 1; i <= app.project.numItems; i++) { var it = app.project.item(i); if (it instanceof FolderItem && it.name == "rml2ae tidy" && (!root || it.parentFolder.id == root.id)) return it; }
  if (!root) return null;
  var f = app.project.items.addFolder("rml2ae tidy"); f.parentFolder = root; return f;
}
function tidyChunks(store) {
  var out = [];
  for (var i = 1; i <= app.project.numItems; i++) { var it = app.project.item(i); if (it instanceof FolderItem && it.parentFolder.id == store.id && /^\d+$/.test(it.name)) out.push(it); }
  out.sort(function (a, b) { return parseInt(a.name, 10) - parseInt(b.name, 10); });
  return out;
}
function tidyLoad(store) {
  if (!store) return {};
  var ch = tidyChunks(store), txt = "";
  for (var i = 0; i < ch.length; i++) txt += ch[i].comment || "";
  if (!txt) return {};
  try { return eval("(" + txt + ")"); } catch (e) { return {}; }
}
function tidySave(store, txt) {
  var ch = tidyChunks(store), n = 0;
  for (var i = 0; i < txt.length || n == 0; i += 15000) {
    var it = n < ch.length ? ch[n] : app.project.items.addFolder(String(n + 1));
    it.parentFolder = store; it.comment = txt.substr(i, 15000); n++;
  }
  for (var k = ch.length - 1; k >= n; k--) ch[k].remove();
}
// AE re-expresses a child in its new parent's space at the comp's current time: with an ancestor scaled to 0 at that
// time the result is garbage (measured: a cigar's glow under a "pop-in" group keyed from scale 0 vanished). The
// dissolved null is static, so any time where the whole new chain is invertible gives the same, exact result.
function tidyChainOk(L, t) {
  for (var X = L; X; X = X.parent) {
    var s = X.property("ADBE Transform Group").property("ADBE Scale").valueAtTime(t, false);
    if (Math.abs(s[0] * s[1]) < 1e-6) return false;
  }
  return true;
}
function tidyTime(comp, P) {
  if (!P) return comp.time;
  var cand = [comp.time, 0, comp.duration / 2, comp.duration - comp.frameDuration];
  for (var X = P; X; X = X.parent) {
    var sp = X.property("ADBE Transform Group").property("ADBE Scale");
    for (var k = 1; k <= sp.numKeys; k++) { cand.push(sp.keyTime(k)); if (k < sp.numKeys) cand.push((sp.keyTime(k) + sp.keyTime(k + 1)) / 2); }
  }
  for (var i = 0; i < cand.length; i++) if (cand[i] >= 0 && cand[i] <= comp.duration && tidyChainOk(P, cand[i])) return cand[i];
  return null;
}
"""

TIDY_BUILD_JSX = r"""
function tidyStatic(L, allowPropagate, ignoreOpacity) {
  var g = L.property("ADBE Transform Group");
  for (var i = 1; i <= g.numProperties; i++) {
    var p = g.property(i);
    if (ignoreOpacity && p.matchName == "ADBE Opacity") continue;
    try { if (p.numKeys > 0) return false; } catch (e) {}
    try { if (p.expressionEnabled && p.expression) { if (!(allowPropagate && p.matchName == "ADBE Opacity" && p.expression == PROPAGATE)) return false; } } catch (e2) {}
  }
  return true;
}
function tidyMovable(C, sx, sy) {
  if (C.threeDLayer) return false;
  var g = C.property("ADBE Transform Group");
  var names = ["ADBE Anchor Point", "ADBE Position", "ADBE Position_0", "ADBE Position_1", "ADBE Rotate Z", "ADBE Scale"];
  for (var i = 0; i < names.length; i++) { try { var p = g.property(names[i]); if (p && p.expressionEnabled && p.expression) return false; } catch (e) {} }
  if (Math.abs(sx - sy) > 1e-6) { var r = g.property("ADBE Rotate Z"); if (r.numKeys > 0 || Math.abs(r.value) > 1e-9) return false; }   // skew
  return true;
}
var TIDY_LIFTED = 0;
// a time remap that maps every time to itself (rml2ae's clip and stepped comps): the layer plays its comp as is
function tidyIdentityRemap(L) {
  var p = L.property("ADBE Time Remapping");
  if (p.expressionEnabled && p.expression) return false;
  // 1 ms: a nested animation's remap starts at Rive's own `time` (0.17 ms on a film), a 1/250 of a frame
  for (var k = 1; k <= p.numKeys; k++) { if (Math.abs(p.keyValue(k) - p.keyTime(k)) > 1e-3) return false; if (p.keyOutInterpolationType(k) == KeyframeInterpolationType.HOLD && k < p.numKeys) return false; }
  return p.numKeys >= 2 || (p.numKeys == 0);
}
// value, keys (times, values, interpolation types, eases) and expression of p copied onto q (same dimension)
function tidyCopyProp(p, q) {
  while (q.numKeys > 0) q.removeKey(1);
  if (p.numKeys == 0) q.setValue(p.value);
  for (var k = 1; k <= p.numKeys; k++) q.setValueAtTime(p.keyTime(k), p.keyValue(k));
  for (var k2 = 1; k2 <= p.numKeys; k2++) {
    q.setTemporalEaseAtKey(k2, p.keyInTemporalEase(k2), p.keyOutTemporalEase(k2));
    q.setInterpolationTypeAtKey(k2, p.keyInInterpolationType(k2), p.keyOutInterpolationType(k2));
  }
  q.expression = (p.expressionEnabled && p.expression) ? p.expression : "";
}
function tidyNoKeys(p) { try { return p.numKeys == 0 && !(p.expressionEnabled && p.expression); } catch (e) { return true; } }
// a precomp holding ONE layer, used by ONE plain layer U (no time remap, no effect, no mask, opacity 100 or the
// propagation expression): that layer goes up into U's comp, where U was, with U's track matte — AE keeps its world
// transform (it is parented to U without compensation, then to U's parent with it). Measured on a 72 s film: 206 of
// the 362 comps were such wrappers (a clip whose content had become one layer once its root null was dissolved).
function tidyLift(comps, rec) {
  var lifted = 0, again = true, dead = {};
  while (again) {
    again = false;
    for (var c = 0; c < comps.length; c++) {
      var P = comps[c];
      if (dead[c]) continue;
      try { if (P.numLayers != 1) continue; } catch (eD) { dead[c] = true; continue; }
      var X = P.layer(1), users = P.usedIn;
      if (users.length != 1) continue;
      var C = users[0], U = null, nU = 0;
      for (var j = 1; j <= C.numLayers; j++) { var L = C.layer(j); try { if (L.source === P) { U = L; nU++; } } catch (e) {} }
      if (nU != 1) continue;
      // only a clip precomp of the same animation as its user ("rive:<node>|<anim>|clip" inside "rive:<…>|<anim>…"): a
      // nested artboard's comp holds another animation's keys (ae pull, incremental builds) — measured: 8 false edits
      var pt = (P.comment || "").split("|"), ct = (C.comment || "").split("|");
      if (pt.length != 3 || pt[2] != "clip" || ct.length < 2 || pt[1] != ct[1]) continue;
      if (X.threeDLayer || X.hasTrackMatte || X.isTrackMatte || X.parent || X.guideLayer) continue;
      if ((U.timeRemapEnabled && !tidyIdentityRemap(U)) || Math.abs(U.startTime) > 1e-9 || Math.abs(U.stretch - 100) > 1e-9 || U.collapseTransformation || U.threeDLayer || U.isTrackMatte || !U.enabled) continue;
      if (U.property("ADBE Effect Parade").numProperties > 0 || U.property("ADBE Mask Parade").numProperties > 0) continue;
      // U's opacity (the clipped node's: value, keys, propagation expression) moves onto the lifted layer when that
      // layer's own opacity is a plain 100 %; ae pull then reads it as the node's (tidy store key "op:…")
      var uo = U.property("ADBE Transform Group").property("ADBE Opacity");
      var uOwn = uo.numKeys > 0 || Math.abs(uo.value - 100) > 1e-6 || (uo.expressionEnabled && uo.expression);
      var xo = X.property("ADBE Transform Group").property("ADBE Opacity");
      if (uOwn && (!tidyNoKeys(xo) || Math.abs(xo.value - 100) > 1e-6)) continue;
      if (U.blendingMode != BlendingMode.NORMAL && X.blendingMode != BlendingMode.NORMAL) continue;
      var t0 = tidyTime(C, U); if (t0 === null) continue;
      var tKeep = C.time; if (Math.abs(C.time - t0) > 1e-9) C.time = t0;
      var M = U.hasTrackMatte ? U.trackMatteLayer : null, mt = U.trackMatteType;
      var before = {}; for (var b = 1; b <= C.numLayers; b++) before[C.layer(b).id] = true;
      X.copyToComp(C);
      var Y = null; for (var b2 = 1; b2 <= C.numLayers; b2++) if (!before[C.layer(b2).id]) { Y = C.layer(b2); break; }
      if (!Y || Y === U) { if (Math.abs(C.time - tKeep) > 1e-9) C.time = tKeep; continue; }
      try {
        Y.setParentWithJump(U);                         // X's values are in P's space, which U maps into C
        Y.parent = U.parent;                            // AE re-expresses Y in U's parent's space (keys included)
        Y.moveBefore(U);
        if (M) Y.setTrackMatte(M, mt);
        Y.inPoint = Math.max(X.inPoint, U.inPoint); Y.outPoint = Math.min(X.outPoint, U.outPoint);
        if (U.blendingMode != BlendingMode.NORMAL) Y.blendingMode = U.blendingMode;
        if (uOwn) { tidyCopyProp(uo, Y.property("ADBE Transform Group").property("ADBE Opacity")); rec["op:" + C.id + ":" + Y.id] = [[U.comment || ""]]; }
        if (!Y.comment) Y.comment = X.comment;
        var kU = C.id + ":" + U.id, kX = P.id + ":" + X.id;
        rec[C.id + ":" + Y.id] = [tidyTf(U)].concat(rec[kX] || []);   // U's current values carry its dissolved parents
        delete rec[kU]; delete rec[kX];
        if (Math.abs(C.time - tKeep) > 1e-9) C.time = tKeep;
      } catch (eL) { try { delete rec[C.id + ":" + Y.id]; Y.remove(); } catch (eY) {} dead[c] = true; if (Math.abs(C.time - tKeep) > 1e-9) C.time = tKeep; continue; }
      U.remove(); dead[c] = true; P.remove(); lifted++; again = true;
      break;
    }
  }
  return lifted;
}
// dissolve the static nulls of the comps under `root`; returns the number removed
function tidyProject(root) {
  var store = tidyStore(root), rec = tidyLoad(store), removed = 0, live = {};
  var comps = [];
  for (var i = 1; i <= app.project.numItems; i++) {
    var it = app.project.item(i);
    if (!(it instanceof CompItem)) continue;
    var f = it.parentFolder; while (f && f !== app.project.rootFolder && f.id != root.id) f = f.parentFolder;
    if (f && f.id == root.id) comps.push(it);
  }
  for (var c = 0; c < comps.length; c++) {
    var comp = comps[c], again = true, tKeep = comp.time;
    while (again) {
      again = false;
      for (var j = comp.numLayers; j >= 1; j--) {
        var N = comp.layer(j);
        if (!N.nullLayer || N.threeDLayer || N.name == "ViewModel" || N.isTrackMatte || N.hasTrackMatte) continue;
        if (N.property("ADBE Effect Parade").numProperties > 0) continue;
        var g = N.property("ADBE Transform Group");
        var s = g.property("ADBE Scale").value, kids = [], ok = true, reads = false;
        for (var k = 1; k <= comp.numLayers; k++) {
          var C = comp.layer(k);
          if (!(C.parent && C.parent.index == N.index)) continue;
          kids.push(C); if (!tidyMovable(C, s[0], s[1])) ok = false;
          try { var ce = C.property("ADBE Transform Group").property("ADBE Opacity").expression; if (ce && ce.indexOf("thisLayer.parent.transform.opacity") >= 0) reads = true; } catch (e4) {}
        }
        // a null with no child goes whatever it carries; else it must be static, and its opacity only matters when a
        // child reads it (Rive's opacity multiplied down)
        if (kids.length && (!ok || !tidyStatic(N, true, !reads))) continue;
        if (reads && Math.abs(g.property("ADBE Opacity").value - 100) > 1e-6) continue;
        var P = N.parent, tf = tidyTf(N);
        if (kids.length) {
          var sN = g.property("ADBE Scale").value; if (Math.abs(sN[0] * sN[1]) < 1e-6) continue;   // a null at scale 0 hides its children
          var t0 = tidyTime(comp, P); if (t0 === null) continue;
          if (Math.abs(comp.time - t0) > 1e-9) comp.time = t0;
        }
        for (var q = 0; q < kids.length; q++) {
          var C2 = kids[q], key = comp.id + ":" + C2.id;
          rec[key] = [tf].concat(rec[key] || []);         // tf: N's CURRENT values, which already carry its own dissolved parents
          C2.parent = P;                                   // AE keeps the world transform (keys re-expressed)
          if (!P) { var op = C2.property("ADBE Transform Group").property("ADBE Opacity"); try { if (op.expression == PROPAGATE) op.expression = ""; else if (op.expression.indexOf(" * thisLayer.parent.transform.opacity / 100") > 0) op.expression = op.expression.replace(/^\((.*)\) \* thisLayer\.parent\.transform\.opacity \/ 100$/, "$1"); } catch (e3) {} }
        }
        delete rec[comp.id + ":" + N.id];
        var nsrc = N.source; N.remove(); removed++; again = true;
        try { if (nsrc && nsrc.usedIn.length == 0) nsrc.remove(); } catch (e5) {}     // its solid, else left orphan
        break;
      }
    }
    if (Math.abs(comp.time - tKeep) > 1e-9) comp.time = tKeep;
  }
  var lifted = 0; try { lifted = tidyLift(comps, rec); } catch (eLift) {}
  var alive = [];
  for (var c2 = 0; c2 < comps.length; c2++) {
    var cc = comps[c2]; try { if (!cc.numLayers && cc.numLayers !== 0) continue; } catch (eR) { continue; }   // removed
    alive.push(cc);
    for (var m = 1; m <= cc.numLayers; m++) live[cc.id + ":" + cc.layer(m).id] = true;
  }
  comps = alive;
  TIDY_LIFTED = lifted;
  var kept = {};
  for (var key2 in rec) { var bare = key2.indexOf("op:") == 0 ? key2.substr(3) : key2, cid = parseInt(bare.split(":")[0], 10), keep = live[bare]; if (!keep) { var inTree = false; for (var z = 0; z < comps.length; z++) if (comps[z].id == cid) inTree = true; keep = !inTree && !!app.project.itemByID(cid); } if (keep) kept[key2] = rec[key2]; }
  tidySave(store, tidySer(kept));
  return removed;
}
"""

# pull: the dissolved nulls are rebuilt around a child while it is read, then removed (AE re-expresses it both ways)
TIDY_PULL_JSX = r"""
function tidyRotated(ch) { for (var i = 0; i < ch.length; i++) if (Math.abs(ch[i][4]) > 1e-9) return true; return false; }
// without rotation the inverse is done in Python on the dumped values (rml2ae/pull.py untidy): no layer created here
function tidyWrap(comp, L, rec) {
  var ch = rec[comp.id + ":" + L.id]; if (!ch || !ch.length || !tidyRotated(ch)) return null;
  var orig = L.parent, cur = orig, tmp = [], tKeep = comp.time;
  var t0 = tidyTime(comp, orig); if (t0 === null) return null;
  if (Math.abs(comp.time - t0) > 1e-9) comp.time = t0;
  for (var i = 0; i < ch.length; i++) {
    var n = comp.layers.addNull(), t = n.property("ADBE Transform Group"), v = ch[i];
    n.parent = cur;
    t.property("ADBE Anchor Point").setValue([v[0], v[1]]); t.property("ADBE Position").setValue([v[2], v[3]]);
    t.property("ADBE Rotate Z").setValue(v[4]); t.property("ADBE Scale").setValue([v[5], v[6]]);
    tmp.push(n); cur = n;
  }
  L.parent = cur;
  return { L: L, orig: orig, tmp: tmp, comp: comp, t: tKeep };
}
function tidyUnwrap(w) {
  if (!w) return;
  w.L.parent = w.orig;
  for (var i = w.tmp.length - 1; i >= 0; i--) { var src = w.tmp[i].source; w.tmp[i].remove(); try { if (src && src.usedIn.length == 0) src.remove(); } catch (e) {} }
  w.comp.time = w.t;
}
"""
