"""ExtendScript (ES3) emitter: JS literals, the runtime prelude (keyframes with Rive eases, layers, text, mattes)."""
import math


def js(v):
    """Python -> JS literal, ASCII only (ExtendScript mangles UTF-8)."""
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        if isinstance(v, float) and (math.isnan(v) or math.isinf(v)):
            v = 0.0
        s = f"{v:.6f}".rstrip("0").rstrip(".") if isinstance(v, float) else str(v)
        return s if s not in ("", "-0") else "0"
    if isinstance(v, str):
        out = []
        for ch in v:
            o = ord(ch)
            if ch == '"':
                out.append('\\"')
            elif ch == "\\":
                out.append("\\\\")
            elif ch == "\n":
                out.append("\\n")
            elif ch == "\r":
                out.append("\\r")
            elif 32 <= o < 127:
                out.append(ch)
            else:
                out.append(f"\\u{o:04x}")
        return '"' + "".join(out) + '"'
    if isinstance(v, (list, tuple)):
        return "[" + ",".join(js(x) for x in v) + "]"
    if isinstance(v, dict):
        return "{" + ",".join(f"{js(str(k))}: {js(x)}" for k, x in v.items()) + "}"
    if v is None:
        return "null"
    raise TypeError(type(v))


class Writer:
    def __init__(self):
        self.lines = []
        self.n = 0

    def var(self, prefix="v"):
        self.n += 1
        return f"{prefix}{self.n}"

    def __call__(self, line):
        self.lines.append(line)

    def text(self):
        return "\n".join(self.lines)


# Every rule below was measured in AE 2026 (see RIVE_FILM_GUIDELINES.md §5): keyframe times are comp times,
# interpolation types BEZIER first then eases then HOLD last, `parent` keeps the child's world transform, nulls are
# solids at opacity 0, temporal eases of Scale on a 2D layer are 3-dimensional.
PRELUDE = r"""
// ---- generated by rml2ae — regenerate, do not edit ----
var FPS = __FPS__;
var LOGF = new File(__LOG__);
LOGF.open("w"); LOGF.close();
function log(s) { LOGF.open("a"); LOGF.write(s + "\n"); LOGF.close(); }
function T(f) { return f / FPS; }
function clamp(v, a, b) { return v < a ? a : (v > b ? b : v); }
function tr(layer, name) { return layer.property("ADBE Transform Group").property(name); }
// a child inherits its parent's opacity (Rive semantics); a data-binding expression already on the child is kept and multiplied
function propagateOpacity(layer) {
  var op = tr(layer, "ADBE Opacity"); var e = op.expression;
  if (e && e.indexOf("thisLayer.parent.transform.opacity") >= 0) return;
  op.expression = e ? "(" + e + ") * thisLayer.parent.transform.opacity / 100" : "value * thisLayer.parent.transform.opacity / 100";
}
// ---- element tags (incremental rebuilds): every layer of an element carries its Rive id in `comment`
// (main layer: "rive:<id>", helpers: "rive:<id>+…"); the comp background carries "head+"
function layerTag(comp, tag) { if (!comp) return null; for (var i = 1; i <= comp.numLayers; i++) if (comp.layer(i).comment == tag) return comp.layer(i); return null; }
function hasTag(L, tags) { var c = L.comment || ""; if (!c) return false; for (var k = 0; k < tags.length; k++) if (c == tags[k] || c.indexOf(tags[k] + "+") == 0) return true; return false; }
function layerIds(comp) { var m = {}; if (!comp) return m; for (var i = 1; i <= comp.numLayers; i++) m[comp.layer(i).id] = true; return m; }
function newLayers(comp, ids) {               // the layers added since the `ids` snapshot, top to bottom (wherever they are)
  var out = []; if (!comp) return out;
  for (var i = 1; i <= comp.numLayers; i++) { var L = comp.layer(i); if (!ids[L.id]) out.push(L); }
  return out;
}
function tagNew(comp, ids, tag, main) {          // the layers added since `ids` belong to `tag`
  var Ls = newLayers(comp, ids);
  for (var i = 0; i < Ls.length; i++) { var L = Ls[i]; if (main && L === main) L.comment = tag; else if (!L.comment) L.comment = tag + "+"; else if (L.comment == tag) L.comment = tag + "+dup"; roleLabel(L); }
}
// one label per role, the same in every project (audit F27: only nulls had one, the rest took this machine's defaults):
// shape 8 blue, text 2 yellow, footage 13 fuchsia, precomp 15 sandstone, colour solid 7 sea foam, baked (replay /
// skinned) 12 brown; technical helpers (mattes, clip duplicates, feather solids) 0 none + shy — hidden in one click
// with the comp's shy switch; nulls keep their role label (controller 3, bone 10, placeholder 4, ViewModel 9)
function roleLabel(L) {
  try {
    var c = L.comment || "", n = L.name || "";
    if (c.indexOf("+matte") >= 0 || c.indexOf("+dup") >= 0 || c.indexOf("+feather") >= 0 || n.indexOf("(matte)") >= 0) { L.label = 0; L.shy = true; return; }
    if (n.indexOf("[replay]") == 0 || n.indexOf("[skinned]") >= 0) { L.label = 12; return; }
    if (L.nullLayer) return;
    if (L instanceof ShapeLayer) { L.label = 8; return; }
    if (L instanceof TextLayer) { L.label = 2; return; }
    if (L.source instanceof CompItem) { L.label = 15; return; }
    if (L.source && L.source.mainSource instanceof SolidSource) { L.label = 7; return; }
    L.label = 13;
  } catch (e) {}
}
function removeTagged(comp, tags) { var n = 0; if (!comp) return 0; for (var i = comp.numLayers; i >= 1; i--) if (hasTag(comp.layer(i), tags)) { comp.layer(i).remove(); n++; } return n; }
function topOf(comp, tags) { if (!comp) return null; for (var i = 1; i <= comp.numLayers; i++) if (hasTag(comp.layer(i), tags)) return comp.layer(i); return null; }
function belowOf(comp, tags) {                   // {below: layer under the lowest tagged one (null = bottom)} or null if none
  var low = 0; if (!comp) return null; for (var i = 1; i <= comp.numLayers; i++) if (hasTag(comp.layer(i), tags)) low = i;
  if (!low) return null; return { below: low < comp.numLayers ? comp.layer(low + 1) : null };
}
// where a rebuilt element goes in the stack: where its old layers were, else above the previous sibling, else at the
// bottom of its parent's subtree, else above the comp background (null = bottom of the comp)
function anchor(comp, own, prev, par) {
  var r = belowOf(comp, own); if (r) return r.below;
  if (prev.length) { var t = topOf(comp, prev); if (t) return t; }
  if (par.length) { r = belowOf(comp, par); if (r) return r.below; }
  return topOf(comp, ["head"]);
}
function placeNew(comp, ids, below) {           // the layers added since `ids` move as a block to sit right above `below`
  var Ls = newLayers(comp, ids); var k = Ls.length; if (k <= 0) return;
  for (var i = 0; i < k; i++) if (Ls[i] === below) { below = (i + 1 < k) ? null : below; if (below === null) { log("placeNew: anchor is a new layer, block left in place"); return; } }
  if (below) Ls[k - 1].moveBefore(below); else Ls[k - 1].moveToEnd();
  for (var j = k - 2; j >= 0; j--) Ls[j].moveBefore(Ls[j + 1]);
}
function propUnder(comp, ids, par) {            // new layers parented to `par` read its opacity (Rive multiplies it down)
  if (!par) return; var Ls = newLayers(comp, ids);
  for (var i = 0; i < Ls.length; i++) if (Ls[i].parent && Ls[i].parent.index == par.index) propagateOpacity(Ls[i]);
}
// an AE effect declared in the RML (<!-- ae: … -->, rml2ae/effects.py): matchName + parameter slots
function addFx(L, match, params) {
  var fx = L.property("ADBE Effect Parade").addProperty(match);
  for (var k in params) { try { fx.property(k).setValue(params[k]); } catch (e) { log("effect " + match + " param " + k + ": " + e.toString()); } }
  return fx;
}
function resetProp(p, v) { while (p.numKeys > 0) p.removeKey(1); p.expression = ""; p.setValue(v); }
// a clip source copy turned into the stencil of its clipped precomp: geometry only (Rive clips by the path, not by its
// paint): fills opaque and unkeyed, strokes removed, layer opacity 100, Stencil Alpha, on top of the precomp's stack
function stencilize(L) {
  function walk(g) {
    for (var i = g.numProperties; i >= 1; i--) {
      var q = g.property(i), mn = q.matchName;
      if (mn == "ADBE Vector Graphic - Stroke") { q.remove(); continue; }
      if (mn == "ADBE Vector Graphic - Fill") { resetProp(q.property("ADBE Vector Fill Opacity"), 100); continue; }
      if (mn == "ADBE Vector Group") walk(q.property("ADBE Vectors Group"));
    }
  }
  try { walk(L.property("ADBE Root Vectors Group")); } catch (e) {}
  resetProp(tr(L, "ADBE Opacity"), 100);
  L.blendingMode = BlendingMode.STENCIL_ALPHA;
  L.moveToBeginning();
}
function sep(layer) { tr(layer, "ADBE Position").dimensionsSeparated = true; }
// after `layer.parent = X` AE rewrites the child's transform to keep its world transform: reset it explicitly
function resetTf(layer, ax, ay, x, y) {
  tr(layer, "ADBE Anchor Point").setValue([ax, ay]); tr(layer, "ADBE Position").setValue([x, y]);
  tr(layer, "ADBE Rotate Z").setValue(0); tr(layer, "ADBE Scale").setValue([100, 100]);
}
// the Rive Shader plugin (rml2ae/plugin) runs .wgsl post-process shaders as is when it is installed
var RIVE_SHADER = (function () { try { for (var i = 0; i < app.effects.length; i++) { if (app.effects[i].matchName == "RIVE RiveShader") return true; } } catch (e) {} return false; })();
// ---- passes for the Rive Shader plugin: clone a comp tree bound to a ViewModel copy with overridden values
// expression sources keep the \uXXXX escapes rml2ae wrote: match both the escaped and the raw spelling of a name
function jsEsc(s) { var o = ""; for (var i = 0; i < s.length; i++) { var c = s.charCodeAt(i); o += c > 127 ? "\\u" + ("0000" + c.toString(16)).slice(-4) : s.charAt(i); } return o; }
function compByName(n) { for (var i = 1; i <= app.project.numItems; i++) { var it = app.project.item(i); if (it instanceof CompItem && it.name == n) return it; } return null; }
function cloneVm(vmComp, newName, overrides) {
  var d = vmComp.duplicate(); d.name = newName;
  var L = d.layer("ViewModel"); if (!L) return d;
  for (var k in overrides) {
    var fx = L.property("ADBE Effect Parade").property(k); if (!fx) { log("cloneVm: no VM property " + k); continue; }
    var v = overrides[k];
    if (fx.matchName == "ADBE Checkbox Control") fx.property(1).setValue(v ? 1 : 0);
    else if (fx.matchName == "ADBE Slider Control") fx.property(1).setValue(Number(v));
    else if (fx.matchName == "ADBE Color Control") fx.property(1).setValue(v);
  }
  return d;
}
function rewriteExpr(prop, pairs) {
  for (var i = 1; i <= prop.numProperties; i++) {
    var q = prop.property(i);
    if (q.propertyType == PropertyType.PROPERTY) {
      try { if (q.canSetExpression && q.expression) { var e = q.expression, e0 = e; for (var j = 0; j < pairs.length; j++) e = e.split(pairs[j][0]).join(pairs[j][1]); if (e != e0) q.expression = e; } } catch (er) {}
    } else rewriteExpr(q, pairs);
  }
}
function setVm(vmComp, overrides) {
  var L = vmComp.layer("ViewModel"); if (!L) return;
  for (var k in overrides) {
    var fx = L.property("ADBE Effect Parade").property(k); if (!fx) { log("setVm: no VM property " + k); continue; }
    var v = overrides[k];
    if (fx.matchName == "ADBE Checkbox Control") fx.property(1).setValue(v ? 1 : 0);
    else if (fx.matchName == "ADBE Slider Control") fx.property(1).setValue(Number(v));
    else if (fx.matchName == "ADBE Color Control") fx.property(1).setValue(v);
  }
}
function exprMentions(prop, pairs) {
  for (var i = 1; i <= prop.numProperties; i++) {
    var q = prop.property(i);
    if (q.propertyType == PropertyType.PROPERTY) {
      try { if (q.canSetExpression && q.expression) { for (var j = 0; j < pairs.length; j++) if (q.expression.indexOf(pairs[j][0]) >= 0) return true; } } catch (er) {}
    } else if (exprMentions(q, pairs)) return true;
  }
  return false;
}
// does `comp` (or a comp below it) read one of the VM comps of `pairs` through an expression? (memo by comp id)
function dependsOnVm(comp, pairs, memo) {
  if (memo[comp.id] !== undefined) return memo[comp.id];
  memo[comp.id] = false;
  var r = false;
  for (var i = 1; i <= comp.numLayers && !r; i++) {
    var L = comp.layer(i);
    if (L.source instanceof CompItem && dependsOnVm(L.source, pairs, memo)) r = true;
    else if (exprMentions(L, pairs)) r = true;
  }
  memo[comp.id] = r;
  return r;
}
// duplicate `comp` and every comp reachable through its layers that reads the ViewModel (not the VM comps, reached by
// expressions only; comps that never read it stay shared, audit F1), then point every expression at the VM copy
// (pairs = [[from, to], ...]); memo keeps shared precomps shared
function cloneTree(comp, suffix, pairs, memo, dep) {
  if (memo[comp.id]) return memo[comp.id];
  if (!dep) dep = {};
  if (!dependsOnVm(comp, pairs, dep)) return comp;
  var d = comp.duplicate(); d.name = comp.name + " [" + suffix + "]"; d.parentFolder = comp.parentFolder; memo[comp.id] = d;
  for (var i = 1; i <= d.numLayers; i++) {
    var L = d.layer(i);
    if (L.source instanceof CompItem) { var c2 = cloneTree(L.source, suffix, pairs, memo, dep); if (c2.id != L.source.id) L.replaceSource(c2, false); }
  }
  for (var i = 1; i <= d.numLayers; i++) rewriteExpr(d.layer(i), pairs);
  return d;
}
function slider(layer, name, value) {
  var fx = layer.property("ADBE Effect Parade").addProperty("ADBE Slider Control");
  fx.name = name; fx.property("ADBE Slider Control-0001").setValue(value); return fx.property("ADBE Slider Control-0001");
}
// footage is reused when the same file is already in the project (incremental rebuilds never duplicate imports)
function importFile(path) {
  var f = new File(path);
  if (!f.exists) throw new Error("missing file " + path);
  for (var i = 1; i <= app.project.numItems; i++) {
    var it = app.project.item(i);
    try { if (it instanceof FootageItem && it.file && it.file.fsName == f.fsName) return it; } catch (e) {}
  }
  return app.project.importFile(new ImportOptions(f));
}
function folder(parent, name) {
  for (var i = 1; i <= app.project.numItems; i++) {
    var it = app.project.item(i);
    if (it instanceof FolderItem && it.name == name && ((parent && it.parentFolder.id == parent.id) || (!parent && it.parentFolder == app.project.rootFolder))) return it;
  }
  var f = app.project.items.addFolder(name); if (parent) f.parentFolder = parent; return f;
}
// comps we made, by their "rive:…" / "vm:…" comment tag
function compTags() {
  var m = {};
  for (var i = 1; i <= app.project.numItems; i++) {
    var it = app.project.item(i);
    if (it instanceof CompItem && it.comment && (it.comment.indexOf("rive:") == 0 || it.comment.indexOf("vm:") == 0)) m[it.comment] = it;
  }
  return m;
}
// helper comps (no rive tag) in a folder that nothing uses any more
function cleanupUnused(folderItem) {
  var n = 0;
  for (var i = app.project.numItems; i >= 1; i--) {
    var it = app.project.item(i);
    if (it instanceof CompItem && it.parentFolder && it.parentFolder.id == folderItem.id && !(it.comment && it.comment.length) && it.usedIn.length == 0) { it.remove(); n++; }
  }
  if (n) log("removed " + n + " unused helper comp(s)");
}
// every layer that uses oldComp as its source now uses newComp (its transform, effects and keys are untouched)
function relinkComp(oldComp, newComp) {
  var n = 0;
  for (var i = 1; i <= app.project.numItems; i++) {
    var it = app.project.item(i);
    if (!(it instanceof CompItem) || it === oldComp) continue;
    for (var j = 1; j <= it.numLayers; j++) {
      var L = it.layer(j);
      try { if (L.source && L.source === oldComp) { L.replaceSource(newComp, false); n++; } } catch (e) {}
    }
  }
  log("relinked " + n + " layer(s) of " + newComp.name);
}
function shapeFrom(verts, ins, outs, closed) {
  var s = new Shape(); s.vertices = verts; s.inTangents = ins; s.outTangents = outs; s.closed = closed; return s;
}
var BLEND = { srcOver: BlendingMode.NORMAL, screen: BlendingMode.SCREEN, overlay: BlendingMode.OVERLAY, darken: BlendingMode.DARKEN,
  lighten: BlendingMode.LIGHTEN, colorDodge: BlendingMode.COLOR_DODGE, colorBurn: BlendingMode.COLOR_BURN, hardLight: BlendingMode.HARD_LIGHT,
  softLight: BlendingMode.SOFT_LIGHT, difference: BlendingMode.DIFFERENCE, exclusion: BlendingMode.EXCLUSION, multiply: BlendingMode.MULTIPLY,
  hue: BlendingMode.HUE, saturation: BlendingMode.SATURATION, color: BlendingMode.COLOR, luminosity: BlendingMode.LUMINOSITY };
// keyframes. ks = [[frame, value, kind, x1, y1, x2, y2], ...]; kind "h" hold / "l" linear / "c" CSS cubic-bezier of the
// segment that STARTS at this key (Rive semantics). Values: number, [x,y], [r,g,b,a] or a Shape.
// time remap: enabling it makes two default keys (0 and the source end) that stay mixed with ours and shift keys()'
// interpolation-by-index (measured: a nested shot starting before its own duration froze on its first frame).
// Set ours first, THEN drop every other key (dropping all keys first would disable the remap).
function dropOtherKeys(p, times) {
  for (var k = p.numKeys; k >= 1; k--) {
    var t = p.keyTime(k), keep = false;
    for (var i = 0; i < times.length; i++) if (Math.abs(times[i] - t) < 1e-4) { keep = true; break; }
    if (!keep) p.removeKey(k);
  }
}
function remapKeys(p, ks) {
  var times = [];
  for (var i = 0; i < ks.length; i++) { p.setValueAtTime(T(ks[i][0]), ks[i][1]); times.push(T(ks[i][0])); }
  dropOtherKeys(p, times);
  keys(p, ks);
}
function remapSet(p, pairs) {
  var times = [];
  for (var i = 0; i < pairs.length; i++) { p.setValueAtTime(pairs[i][0], pairs[i][1]); times.push(pairs[i][0]); }
  dropOtherKeys(p, times);
}
function keys(p, ks) {
  if (ks.length == 0) return;
  if (ks.length == 1) { p.setValue(ks[0][1]); return; }
  var n = ks.length, i;
  for (i = 0; i < n; i++) p.setValueAtTime(T(ks[i][0]), ks[i][1]);
  var B = KeyframeInterpolationType.BEZIER, HLD = KeyframeInterpolationType.HOLD;
  var isShape = (ks[0][1] instanceof Shape);
  if (isShape) { for (i = 0; i < n - 1; i++) if (ks[i][2] == "h") p.setInterpolationTypeAtKey(i + 1, p.keyInInterpolationType(i + 1), HLD); return; }
  var dims = (ks[0][1] instanceof Array) ? ks[0][1].length : 1;
  var spatial = false;
  try { spatial = p.isSpatial; } catch (e) {}
  for (i = 0; i < n; i++) p.setInterpolationTypeAtKey(i + 1, B, B);
  var nEase = p.keyInTemporalEase(1).length;
  var eases = [];
  for (i = 0; i < n; i++) eases.push([p.keyInTemporalEase(i + 1), p.keyOutTemporalEase(i + 1)]);
  for (i = 0; i < n - 1; i++) {
    var kind = ks[i][2];
    if (kind == "h") continue;
    var lin = (kind == "l");
    var x1 = lin ? 0.3333 : ks[i][3], y1 = lin ? 0.3333 : ks[i][4], x2 = lin ? 0.6667 : ks[i][5], y2 = lin ? 0.6667 : ks[i][6];
    var dt = T(ks[i + 1][0]) - T(ks[i][0]);
    var outE = [], inE = [];
    for (var d = 0; d < nEase; d++) {
      var dd = Math.min(d, dims - 1);
      var v0 = dims > 1 ? ks[i][1][dd] : ks[i][1], v1 = dims > 1 ? ks[i + 1][1][dd] : ks[i + 1][1];
      var dv = v1 - v0;
      if (spatial && dims > 1) { dv = 0; for (var q = 0; q < dims; q++) dv += Math.pow(ks[i + 1][1][q] - ks[i][1][q], 2); dv = Math.sqrt(dv); }
      // speed at the influence actually written (0.1 % minimum): a vertical handle (x1 = 0 or x2 = 1) is a very fast
      // start / end, not a zero speed (walk-test: 'Ecran fond' exit was 272 px off with so = 0)
      var ix = Math.max(x1, 0.001), ox = Math.max(1 - x2, 0.001);
      var so = (y1 * dv) / (ix * dt);
      var si = ((1 - y2) * dv) / (ox * dt);
      if (isNaN(so) || !isFinite(so)) so = 0;
      if (isNaN(si) || !isFinite(si)) si = 0;
      outE.push(new KeyframeEase(so, clamp(x1 * 100, 0.1, 100)));
      inE.push(new KeyframeEase(si, clamp((1 - x2) * 100, 0.1, 100)));
    }
    eases[i][1] = outE; eases[i + 1][0] = inE;
  }
  for (i = 0; i < n; i++) { try { p.setTemporalEaseAtKey(i + 1, eases[i][0], eases[i][1]); } catch (e3) {} }
  // a Rive linear segment is LINEAR on both of its sides (the Graph Editor shows a straight line and a retime keeps it);
  // the order BEZIER, eases, then LINEAR / HOLD is the measured one
  var LIN = KeyframeInterpolationType.LINEAR;
  for (i = 0; i < n - 1; i++) if (ks[i][2] == "l") {
    p.setInterpolationTypeAtKey(i + 1, p.keyInInterpolationType(i + 1), LIN);
    p.setInterpolationTypeAtKey(i + 2, LIN, p.keyOutInterpolationType(i + 2));
  }
  // nothing follows the last key: its out side follows its in side instead of a HOLD that bites when extending
  for (i = 0; i < n - 1; i++) if (ks[i][2] == "h") p.setInterpolationTypeAtKey(i + 1, p.keyInInterpolationType(i + 1), HLD);
  if (n > 1) { try { p.setInterpolationTypeAtKey(n, p.keyInInterpolationType(n), p.keyInInterpolationType(n)); } catch (e4) {} }
  if (spatial) { for (i = 1; i <= n; i++) { try { p.setSpatialTangentsAtKey(i, [0, 0], [0, 0]); } catch (e2) {} } }
}
var BOXPOS_LOGGED = false;
function textLayer(comp, txt, font, size, rgb, justify, tracking, leading, boxW, boxH) {
  var L = (boxW > 0) ? comp.layers.addBoxText([boxW, boxH > 0 ? boxH : 4000], txt) : comp.layers.addText(txt);
  var d = L.property("ADBE Text Properties").property("ADBE Text Document");
  var td = d.value;
  td.font = font; td.fontSize = size; td.fillColor = rgb; td.applyFill = true; td.applyStroke = false;
  td.justification = justify; td.tracking = tracking || 0;
  if (leading > 0) { td.autoLeading = false; td.leading = leading; }
  d.setValue(td);
  if (boxW > 0 && !BOXPOS_LOGGED) { BOXPOS_LOGGED = true; try { log("boxTextPos of the first box text: " + d.value.boxTextPos + " size " + d.value.boxTextSize); } catch (eb) { log("boxTextPos unreadable"); } }
  return L;
}
function textStroke(L, rgb, width) {
  var d = L.property("ADBE Text Properties").property("ADBE Text Document"); var td = d.value;
  td.applyStroke = true; td.strokeColor = rgb; td.strokeWidth = width; td.strokeOverFill = false; d.setValue(td);
}
// text animator: props = {pos:[x,y], rot:deg, opacity:0..100, scale:[x,y]} ; sel = {units:"words"|"lines"|"characters", start, end, index:true}
function animator(L, name, props, sel) {
  var an = L.property("ADBE Text Properties").property("ADBE Text Animators").addProperty("ADBE Text Animator");
  an.name = name;
  var ap = an.property("ADBE Text Animator Properties");
  var out = { anim: an };
  if (props.pos !== undefined) out.pos = ap.addProperty("ADBE Text Position 3D");
  if (props.rot !== undefined) out.rot = ap.addProperty("ADBE Text Rotation");
  if (props.opacity !== undefined) out.opacity = ap.addProperty("ADBE Text Opacity");
  if (props.scale !== undefined) out.scale = ap.addProperty("ADBE Text Scale 3D");
  if (out.pos) out.pos.setValue([props.pos[0], props.pos[1], 0]);
  if (out.rot) out.rot.setValue(props.rot);
  if (out.opacity) out.opacity.setValue(props.opacity);
  if (out.scale) out.scale.setValue([props.scale[0], props.scale[1], 100]);
  var s = an.property("ADBE Text Selectors").addProperty("ADBE Text Selector");
  var adv = s.property("ADBE Text Range Advanced");
  var based = { characters: 1, charactersNoSpaces: 2, words: 3, lines: 4 }[sel.units || "characters"];
  adv.property("ADBE Text Range Type2").setValue(based);
  if (sel.index) {
    adv.property("ADBE Text Range Units").setValue(2);
    out.start = s.property("ADBE Text Index Start"); out.end = s.property("ADBE Text Index End");
  } else {
    adv.property("ADBE Text Range Units").setValue(1);
    out.start = s.property("ADBE Text Percent Start"); out.end = s.property("ADBE Text Percent End");
  }
  out.start.setValue(sel.start); out.end.setValue(sel.end);
  out.amount = adv.property("ADBE Text Selector Max Amount");
  return out;
}
// source text keyframes (always hold): rows = [[frame, "text"], ...] — keeps the layer's text style
function textKeys(L, rows) {
  var d = L.property("ADBE Text Properties").property("ADBE Text Document");
  for (var i = 0; i < rows.length; i++) { var td = d.value; td.text = rows[i][1]; d.setValueAtTime(T(rows[i][0]), td); }
}
// per-run style (AE 2024+ characterRange); silently skipped on older versions
function runStyle(L, start, len, font, size, rgb) {
  try {
    var d = L.property("ADBE Text Properties").property("ADBE Text Document"); var td = d.value;
    var cr = td.characterRange(start, start + len);
    if (font) cr.font = font; if (size > 0) cr.fontSize = size; if (rgb) cr.fillColor = rgb;
    d.setValue(td);
  } catch (e) { log("runStyle unsupported on this AE: " + e.toString()); }
}
function selfTest(comp) {
  var n = comp.layers.addNull(); n.name = "__selftest";
  var p = slider(n, "t", 0);
  keys(p, [[0, 0, "c", 0.5, 0, 0.05, 1], [20, 100, "h"], [30, 0, "l"], [40, 50, "h"]]);
  var s = "selftest (expect 19.63 83.07 97.08 100 25):";
  var pr = [5, 10, 15, 25, 35];
  for (var i = 0; i < pr.length; i++) s += " " + p.valueAtTime(T(pr[i]), false).toFixed(2);
  s += " linear=" + (p.keyOutInterpolationType(3) == KeyframeInterpolationType.LINEAR && p.keyInInterpolationType(4) == KeyframeInterpolationType.LINEAR);
  log(s);
  // vertical handles (CSS 0,0.58,0.36,1 and 0.65,0,1,0.4): Rive progress at 0.1 / 0.5 / 0.9
  var q = slider(n, "v", 0);
  keys(q, [[0, 0, "c", 0.001, 0.58, 0.36, 1], [10, 100, "c", 0.65, 0, 0.999, 0.4], [20, 0, "h"]]);
  var s2 = "selftest vertical handles (Rive: 48.25 89.28 99.65 | 99.67 89.87 49.56):";
  var pr2 = [1, 5, 9, 11, 15, 19];
  for (var j = 0; j < pr2.length; j++) s2 += " " + q.valueAtTime(T(pr2[j]), false).toFixed(2);
  log(s2);
  n.remove();
}
"""
